export enum DocStatus {
  READY_FOR_DISPATCH = "READY_FOR_DISPATCH",
  TRIP_SCHEDULED = "TRIP_SCHEDULED",
  ON_TRIP = "ON_TRIP",
  AT_TRANSIT_HUB = "AT_TRANSIT_HUB",
  DELIVERED = "DELIVERED",
  UNDELIVERED = "UNDELIVERED",
}
